<?php

namespace GameBundle\Repository;

/**
 * RessourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourcesRepository extends \Doctrine\ORM\EntityRepository
{
}
