<?php

namespace GameBundle\Repository;

/**
 * UniversRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniversRepository extends \Doctrine\ORM\EntityRepository
{
}
